sonar.projectKey=nonok32_devops
sonar.projectName=DevopsCap
sonar.sourceEncoding=UTF-8

sonar.sources=.
sonar.tests=tests
sonar.test.inclusions=tests/**/*.py
sonar.exclusions=**/.venv/**,**/__pycache__/**,**/txt_files/**,**/infra/terraform/**

sonar.python.coverage.reportPaths=coverage.xml
